### ISSUE TITLE
Batch POST request doesn't create records in the order they are submitted in

### ISSUE THREAD

**Issue by bobringer** [nhl/bootique#36]
A POST request to an endpoint that performs a syncAndSelect() does not create records in the same order they are submitted (for auto incremented ids).

Does this actually matter?

@rzen mentioned that there was a related issue in the past that would return data out of order for that POST request, which appears to be working... but the IDs are not in order so subsequent GET requests do not return the data in that order.  See the example below:

Does this actually matter?

### Request
```
POST /person/ HTTP/1.1
Host: 127.0.0.1:8187
Content-Type: application/json
Cache-Control: no-cache
Postman-Token: b9040f0c-6488-f542-108f-0492559cbd0a

[
    {"firstName":"Bob","lastName":"One"},
    {"firstName":"John","lastName":"Two"},
    {"firstName":"Steven","lastName":"Three"}
]
```

### Response
```
{
    "data": [
        {
            "id": 200,
            "firstName": "Bob",
            "lastName": "One"
        },
        {
            "id": 202,
            "firstName": "John",
            "lastName": "Two"
        },
        {
            "id": 201,
            "firstName": "Steven",
            "lastName": "Three"
        }
    ],
    "total": 3
}
```

**Comment by andrus** [comment]
@bobringer : looks like a LinkRest issue, not Bootique?

**Comment by bobringer** [comment]
Sorry about that... I'll move it.  I'm swimming in both right now.
