### ISSUE TITLE
How does this compare to Spring Boot?

### ISSUE THREAD

**Issue by chenrui333** [nhl/bootique#81]
I did not see this question get posted issues list, but I wonder if anyone can give me a comparison, maybe, it can be put into the documentation for easier adoption.

**Comment by andrus** [comment]
I've touched on this in a few presentations. E.g. https://www.youtube.com/watch?v=o6kSEG4v3VE (towards the end). Briefly: unopinionated small core on top of Google Guice, no integrations hardwired in the core (so services don't activate themselves unexpectedly), everything is a module, even low-level things like logging, POSIX'y command line (easy to build or reuse CLI commands and flags).

**Comment by andrus** [comment]
Closing the issue, as the question is answered. Feel free to ask more questions though (here or via new issues)
